name: "referrer"
repository: github.com/otms61/trivy-plugin-referrer
version: "0.1.2"
usage: upload artifact
description: |-
  A Trivy plugin for oci referrers
  Usage: trivy image -q -f cyclonedx IMAGE_NAME | trivy referrer put
platforms:
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/otms61/trivy-plugin-referrer/releases/download/v0.1.2/trivy_plugin_referrer_0.1.2_macOS-64bit.tar.gz
    bin: ./referrer
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/otms61/trivy-plugin-referrer/releases/download/v0.1.2/trivy_plugin_referrer_0.1.2_macOS-ARM64.tar.gz
    bin: ./referrer
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/otms61/trivy-plugin-referrer/releases/download/v0.1.2/trivy_plugin_referrer_0.1.2_Linux-64bit.tar.gz
    bin: ./referrer
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/otms61/trivy-plugin-referrer/releases/download/v0.1.2/trivy_plugin_referrer_0.1.2_Linux-ARM64.tar.gz
    bin: ./referrer
